[package]
name = "digivoter_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.4"
ic-cdk-timers = "0.1.2"
ic-stable-structures = "0.5.4"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
